# Text that the plugin outputs in game
messages:
  actionbar-off: "&cCam mode ended"
  actionbar-on: "&aCam mode activated"
  armorstand.name-format: "&e{player}'s Body"
  body-attacked: "&cYour body was attacked by {damager}! Camera mode ended."
  body-drowning: "&cYour body is drowning! Camera mode ended."
  body-env-damage: "&cYour body was damaged by {cause}! Camera mode ended."
  body-got-effect: "&cYour body was hit by an effect and camera mode was ended!"
  body-missing: "&cYour body no longer exists! Camera mode ended."
  body-moved: "&cYour body was moved! Camera mode ended."
  body-suffocating: "&cYour body is stuck and suffocating! Camera mode ended."
  bossbar-text: "Cam mode ends in: %time%"
  cam-safety: "§cYou cannot start cam mode! You must remain safe for %seconds% more seconds."
  camera-off: "&aCamera mode ended."
  camera-on: "&aCamera mode activated! Use /cam again to exit."
  cant-attack-other-body: "&cYou cannot attack other bodies in camera mode."
  cant-fly-in-lava: "&cYou cannot fly through lava! Camera mode will be ended."
  cant-interact-other: "&cYou cannot interact with another player's body!"
  cooldown-available: "&aCam mode available again"
  cooldown-text: "You can start cam mode again in %time%."
  distance-limit: "&cYou cannot move further than {distance} blocks from your body!"
  hitbox.name-format: "&c[HITBOX] {player}"
  no-permission: "&cYou don't have permission to use this command."
  no-player: "&cThis command can only be used by players."
  no-projectiles: "&cYou cannot shoot projectiles in camera mode."
  protocol-found: "ProtocolLib found! Sound suppression is enabled."
  reload-exit: "&cCamera mode ended due to plugin restart."
  reload-start: "&ePlugin is restarting..."
  reload-success: "&aPlugin reload successful."
  time-limit-expired: "&cCam mode ended: Time limit expired."

# Enable or disable individual messages
message-settings:
  body-attacked: true
  body-drowning: true
  body-env-damage: true
  body-got-effect: true
  body-missing: true
  body-moved: true
  body-suffocating: true
  bossbar-text: true
  cam-safety: true
  camera-off: false
  camera-on: false
  cant-attack-other-body: true
  cant-fly-in-lava: true
  cant-interact-other: true
  cooldown-available: true
  cooldown-text: true
  distance-limit: true
  enabled: true
  no-permission: true
  no-player: true
  no-projectiles: true
  protocol-found: true
  reload-exit: true
  reload-start: true
  reload-success: true
  time-limit-expired: true

# Settings for the action bar display
action-bar:
  # Determines if the action bar is used
  enabled: true
  # Duration of the fade-out after disabling
  off-duration: 1


# Basic settings of camera mode
camera-mode:
  # Enable the distance limit to the body
  max-distance-enabled: true
  # Maximum distance in blocks
  max-distance: 100.0
  # Cooldown between distance warnings
  distance-warning-cooldown: 3
  # Damage per tick when the body is drowning
  drowning-damage: 2.0
  # Visibility of other players in mode (cam/true/false)
  player_visibility_mode: "true"
  # Allow invisibility potions
  allow_invisibility_potion: true
  # Allow flight through lava
  allow_lava_flight: true

# Armor stand settings
armorstand:
  # Show the name above the armor stand
  name-visible: true
  # Whether the armor stand is visible
  visible: true
  # Gravity for the armor stand
  gravity: true
  # Damage the armor stand receives when hit
  damage-amount: 1.0
  # Reduce durability of equipped armor
  durability-loss: true
  # Ignore armor when calculating damage
  damage-ignore-armor: true

# Sound suppression
mute:
  # Suppress attack sounds
  attack: true
  # Suppress footstep sounds
  footsteps: true
  # Hide sprint particles
  hide-sprint-particles: true

# Limit the duration of camera mode
time-limit:
  # Enable the time limit
  enabled: false
  # Enable a cooldown after expiry
  cooldowns-enabled: false
  # Maximum duration of the mode in seconds
  duration-seconds: 300
  # Wait time until the next start in seconds
  cooldown-seconds: 120
  # Show a boss bar to display the remaining time
  show-bossbar: true
  # Color of the boss bar
  bossbar-color: BLUE

# Particles around the player in camera mode
camera-particles:
  # Vertical position of the particles
  height: 0.2
  # Number of particles per tick
  particles-per-tick: 0.1
  # Show particles to the player themselves
  show-own-particles: false

# Fire protection during camera mode
fireguard:
  # Enable fire protection
  enabled: true
  # Visually hide nearby fire
  hide-fire: true
  # Update interval in ticks
  tick-interval: 10
  # Horizontal search radius
  radius-horizontal: 1.5
  # Vertical radius upward
  radius-up: 2
  # Vertical radius downward
  radius-down: 1

# Put a camera head on the player
camera-head:
  # Enable the camera head
  enabled: false

# Protection against immediate start after taking damage
cam-safety:
  # Enable the safety check
  enabled: true
  # Wait time after last damage in seconds
  delay: 5

# Settings for damage transfer
mirror-damage:
  # Use the player's real armor
  damage-armor: true
  # Type of damage transfer: mirror | custom | off
  damage-mode: mirror  # mirror | custom | off
  # Fixed damage in hearts for the "custom" mode
  custom-damage-hearts: 0.5
