# Texte, die das Plugin im Spiel ausgibt
messages:
  actionbar-off: "&cCam mode ended"
  actionbar-on: "&aCam mode activated"
  armorstand.name-format: "&e{player}'s Body"
  body-attacked: "&cYour body was attacked by {damager}! Camera mode ended."
  body-drowning: "&cYour body is drowning! Camera mode ended."
  body-env-damage: "&cYour body was damaged by {cause}! Camera mode ended."
  body-got-effect: "&cYour body was hit by an effect and camera mode was ended!"
  body-missing: "&cYour body no longer exists! Camera mode ended."
  body-moved: "&cYour body was moved! Camera mode ended."
  body-suffocating: "&cYour body is stuck and suffocating! Camera mode ended."
  bossbar-text: "Cam mode ends in: %time%"
  cam-safety: "§cYou cannot start cam mode! You must remain safe for %seconds% more seconds."
  camera-off: "&aCamera mode ended."
  camera-on: "&aCamera mode activated! Use /cam again to exit."
  cant-attack-other-body: "&cYou cannot attack other bodies in camera mode."
  cant-fly-in-lava: "&cYou cannot fly through lava! Camera mode will be ended."
  cant-interact-other: "&cYou cannot interact with another player's body!"
  cooldown-available: "&aCam mode available again"
  cooldown-text: "You can start cam mode again in %time%."
  distance-limit: "&cYou cannot move further than {distance} blocks from your body!"
  hitbox.name-format: "&c[HITBOX] {player}"
  no-permission: "&cYou don't have permission to use this command."
  no-player: "&cThis command can only be used by players."
  no-projectiles: "&cYou cannot shoot projectiles in camera mode."
  protocol-found: "ProtocolLib found! Sound suppression is enabled."
  reload-exit: "&cCamera mode ended due to plugin restart."
  reload-start: "&ePlugin is restarting..."
  reload-success: "&aPlugin reload successful."
  time-limit-expired: "&cCam mode ended: Time limit expired."

# Aktiviert oder deaktiviert einzelne Nachrichten
message-settings:
  body-attacked: true
  body-drowning: true
  body-env-damage: true
  body-got-effect: true
  body-missing: true
  body-moved: true
  body-suffocating: true
  bossbar-text: true
  cam-safety: true
  camera-off: false
  camera-on: false
  cant-attack-other-body: true
  cant-fly-in-lava: true
  cant-interact-other: true
  cooldown-available: true
  cooldown-text: true
  distance-limit: true
  enabled: true
  no-permission: true
  no-player: true
  no-projectiles: true
  protocol-found: true
  reload-exit: true
  reload-start: true
  reload-success: true
  time-limit-expired: true

# Einstellungen für die Action-Bar Anzeige
action-bar:
  # Legt fest, ob die Action-Bar verwendet wird
  enabled: true
  # Dauer der Ausblendung nach dem Beenden
  off-duration: 1


# Grundeinstellungen des Kamera-Modus
camera-mode:
  # Aktiviert die Begrenzung der Entfernung zum Körper
  max-distance-enabled: true
  # Maximale Entfernung in Blöcken
  max-distance: 100.0
  # Abklingzeit zwischen Distanzwarnungen
  distance-warning-cooldown: 3
  # Schaden pro Tick beim Ertrinken des Körpers
  drowning-damage: 2.0
  # Sichtbarkeit anderer Spieler im Modus (cam/true/false)
  player_visibility_mode: "true"
  # Erlaubt Unsichtbarkeitstränke
  allow_invisibility_potion: true
  # Erlaubt Flug durch Lava
  allow_lava_flight: true

# Einstellungen des Rüstungsständers
armorstand:
  # Zeigt den Namen über dem Rüstungsständer an
  name-visible: true
  # Ob der Rüstungsständer sichtbar ist
  visible: true
  # Schwerkraft für den Rüstungsständer
  gravity: true
  # Schaden, den der Rüstungsständer bei Treffern erhält
  damage-amount: 1.0
  # Verringert Haltbarkeit der ausgerüsteten Rüstung
  durability-loss: true
  # Ignoriert Rüstung beim Berechnen des Schadens
  damage-ignore-armor: true

# Geräuschunterdrückung
mute:
  # Unterdrückt Angriffssounds
  attack: true
  # Unterdrückt Schrittgeräusche
  footsteps: true
  # Versteckt Sprintpartikel
  hide-sprint-particles: true

# Begrenzung der Dauer des Kamera-Modus
time-limit:
  # Aktiviert das Zeitlimit
  enabled: false
  # Aktiviert eine Abklingzeit nach Ablauf
  cooldowns-enabled: false
  # Maximale Dauer des Modus in Sekunden
  duration-seconds: 300
  # Wartezeit bis zum nächsten Start in Sekunden
  cooldown-seconds: 120
  # Zeigt eine Bossbar zur Anzeige der verbleibenden Zeit
  show-bossbar: true
  # Farbe der Bossbar
  bossbar-color: BLUE

# Partikel um den Spieler im Kamera-Modus
camera-particles:
  # Vertikale Position der Partikel
  height: 0.2
  # Anzahl der Partikel pro Tick
  particles-per-tick: 0.1
  # Zeigt Partikel auch dem Spieler selbst an
  show-own-particles: false

# Schutz vor Feuer während des Kamera-Modus
fireguard:
  # Aktiviert den Feuerschutz
  enabled: true
  # Blendete nahe Feuer optisch aus
  hide-fire: true
  # Abstand der Aktualisierung in Ticks
  tick-interval: 10
  # Horizontaler Suchradius
  radius-horizontal: 1.5
  # Vertikaler Radius nach oben
  radius-up: 2
  # Vertikaler Radius nach unten
  radius-down: 1

# Setzt dem Spieler einen Kamera-Kopf auf
camera-head:
  # Aktiviert den Kamerakopf
  enabled: false

# Schutz vor sofortigem Start nach Schaden
cam-safety:
  # Aktiviert die Sicherheitsprüfung
  enabled: true
  # Wartezeit nach letztem Schaden in Sekunden
  delay: 5

# Einstellungen zur Übertragung von Schaden
mirror-damage:
  # Verwendet die echte Rüstung des Spielers
  damage-armor: true
  # Art der Schadensübertragung: mirror | custom | off
  damage-mode: mirror  # mirror | custom | off
  # Fester Schaden in Herzen für den Modus "custom"
  custom-damage-hearts: 0.5